# This is a basic workflow to help you get started with Actions

name: scrape-sg-auto

# Controls when the workflow will run
on:
  schedule:
  - cron: 34 06 * * *           # runs at 03:06 UTC (11:06 SGT) for Regular Menu
  - cron: 33 22 * * *           # runs at 20:33 UTC (04:33 SGT) for Breakfast Menu
concurrency:
  group: scrape-and-schedule
  cancel-in-progress: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout repo content
      uses: actions/checkout@v4       # checkout the repository content to GitHub runner.
    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.14
    - name: setup dependencies
      working-directory: ./mcd-bs4-sg
      run: pip install -r requirements.txt
    - name: execute py script       # run mcd-scr-sg.py to get the latest data
      working-directory: ./mcd-bs4-sg
      run: |
        scrapy crawl mcd-scr-sg
    - name: Commit and push if it changed
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git pull
        git commit -m "Scraped: [${timestamp}] mcd-bs4-sg (auto)" 
        git push "https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD || exit 0
