# This is a basic workflow that is manually triggered

name: scrape-my-manual

# Controls when the workflow will run
on:
  workflow_dispatch

concurrency:
  group: scrape-and-schedule
  cancel-in-progress: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  manual-scrape:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout repo content
      uses: actions/checkout@v4       # checkout the repository content to github runner.
    - name: setup python
      uses: actions/setup-python@v5
      with:
          python-version: '3.10'
    - name: setup dependencies
      working-directory: ./mcd-bs4-my
      run: |
        pip install beautifulsoup4
        pip install pandas
        pip install lxml
        pip install pytz
        pip3 install requests
        pip install path
    - name: execute py script       # run mcd-bs4-my.py to get the latest data
      working-directory: ./mcd-bs4-my
      run: |
        python mcd-req-my.py
    - name: Commit and push if it changed
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Scraped: [${timestamp}] mcd-bs4-my (manual)" 
        git push origin HEAD || exit 0
