# This is a basic workflow that is manually triggered

name: scrape-nz-manual

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "scrape"
  scrape:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
          - name: checkout repo content
            uses: actions/checkout@v2 # checkout the repository content to github runner.
          - name: setup python
            uses: actions/setup-python@v2
            with:
                python-version: 3.8.2
          - name: setup dependencies
            working-directory: ./mcd-scr-nz
            run: |
              pip3 install scrapy
              pip3 install pandas 
              pip3 install pytz
              pip3 install path
              pip3 install pathlib2
          - name: execute py script # run mcd-scr-nz.py to get the latest data
            working-directory: ./mcd-scr-nz
            run: |
              scrapy crawl mcd-scr-nz
          - name: Commit and push if it changed
            run: |
              git config user.name "${GITHUB_ACTOR}"
              git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
              git add -A
              timestamp=$(date -u)
              git commit -m "Scraped: [${timestamp}] mcd-scr-nz (manual)" 
              git push "https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main || exit 0
