# This is a basic workflow to help you get started with Actions

name: scrape-fj-auto

# Controls when the workflow will run
on:
  schedule:
  - cron: 12 15 * * *           # runs once a day at 18:12 UTC (06:12 FJT)
concurrency:
  group: scrape-and-schedule
  cancel-in-progress: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: sparse checkout country file directory
      uses: snow-actions/sparse-checkout@v1.1.0
      with:
        token: ${{ secrets.WORKFLOW_TOKEN }}
        patterns: ./mcd-sel-fj

    - name: setup python
      uses: actions/setup-python@v2
#       with:
#         python-version: 3.8.2
    - name: setup dependencies
      working-directory: ./mcd-sel-fj
      run: |
        pip install selenium
        pip install pandas 
        pip install pytz
        pip3 install requests
        pip install path
        pip install pathlib2
    - name: execute py script       # run mcd-sel-fj.py to get the latest data
      working-directory: ./mcd-sel-fj
      run: |
        python mcd-sel-fj.py
    - name: Commit and push if it changed
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Scraped: [${timestamp}] mcd-sel-fj (auto)" 
        git config --global push.default current
        git push "https://${GITHUB_ACTOR}:${{ secrets.WORKFLOW_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" || exit 0
