# This is a basic workflow that is automatically triggered to run at a specific UTC time each day.

name: scrape-au-auto

# Controls when the action will run
on:
  schedule:
  - cron: 15 21 * * *           # runs once a day at 19:15 UTC (05:15 AEST)

concurrency:
  group: scrape-and-schedule
  cancel-in-progress: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "scrape"
  scrape:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout repo content
      uses: actions/checkout@v3       # checkout the repository content to github runner.
    - name: setup python
      uses: actions/setup-python@v4
#       with:
#         python-version: 3.9.6
    - name: setup dependencies
      working-directory: ./mcd-scr-au
      run: |
        pip3 install scrapy==2.6.1
        pip3 install pandas 
        pip3 install pytz
        pip3 install path
        pip3 install pathlib2
        pip3 install pyopenssl
#       pip3 install pyopenssl==22.0.0
    - name: execute py script       # run mcd-scr-au.py to get the latest data
      working-directory: ./mcd-scr-au
      run: |
        scrapy crawl mcd-scr-au
    - name: Commit and push if it changed
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git pull
        git commit -m "Scraped: [${timestamp}] mcd-scr-au (auto)" 
        git push "https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main || exit 0
